# Generated by Django 3.0 on 2020-07-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('first_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
    ]
